Feat: add desktop version and functionality
Yinkusadel/adel-js-calculator-app pull request #3
Opened 2023-11-05 10:29 UTC by Yinkusadel

2023-11-05 12:56 UTC, moshoodabdullahi requested changes
Everything looks good except for the positioning, try checking this [design](file:///C:/Users/abdullahi/Downloads/calculator-app-main/calculator-app-main/design/desktop-design-theme-1.jpg) and conpare it with your

2023-11-06 11:05 UTC, moshoodabdullahi approved these changes

2023-11-06 12:31 UTC, moshoodabdullahi approved these changes

2023-11-06 13:12 UTC, teckcipher approved these changes

2023-11-06 14:57 UTC, merged