feat: add listener function and button actions
Yinkusadel/adel-js-calculator-app pull request #7
Opened 2023-12-09 16:23 UTC by Yinkusadel

2023-12-10 08:31 UTC, teckcipher requested changes
Here are some edge cases you can fix along with the other review comments 

![image](https://github.com/Yinkusadel/adel-js-calculator-app/assets/123197179/af57238f-96ed-4cfe-aec8-9f6998279155)

2023-12-10 08:31 UTC, teckcipher commented on js/calculate.js
> +      if (!hasDecimal) {
Can you please handle positive can first? For example use `operator === null` instead of `operator !== null` and use `if (hasDecimal) {` instead of `if (!hasDecimal) {`

2023-12-10 08:31 UTC, teckcipher commented on js/calculate.js
> +          num2: operator !== null ? updatedNum : num2,
same here

2023-12-10 08:31 UTC, teckcipher commented on js/calculate.test.js
> +describe('when dividing by zero', () => {
Please fix this title

2023-12-10 08:34 UTC, teckcipher commented on index.html
> +              <div class="user-input d-flex align-center"></div>
Let's use `0` instead.

2023-12-12 09:40 UTC, adejam approved these changes
# LGTM

## Nice job...

PR description can be improved though... using the following
-  acceptance criteria of the task
- adding steps to test
- good format with headers differentiable from paragraphs
- having detailed description of why the task is necessary

2023-12-12 09:56 UTC, teckcipher approved these changes

2023-12-12 11:10 UTC, merged